name: GitHub CI/CD
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.5.0

    - name: Git Checkout
      uses: actions/checkout@v2

    - name: DSharp4Webhook Build
      shell: pwsh -File {0}
      run: ./scripts/build.ps1

    - uses: actions/upload-artifact@v2
      with:
        path: deploy/*.tar.gz

  deploy:
    runs-on: windows-latest
    needs: build
    steps:

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.5.0

    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Generate NuGet file
      run: dotnet pack

    - uses: actions/download-artifact@v2
      with:
        path: deploy

    # Making a release if it is a tag
    - name: GitHub Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: deploy/*.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Push NuGet if it is a tag
    - name: NuGet Push
      if: startsWith(github.ref, 'refs/tags/')
      run: Get-ChildItem -Path "src\" -File -Recurse | Where-Object Name -Match ".+\.nupkg" | % {dotnet nuget push $_.FullName -s nuget.org -k ${{secrets.NUGET_API_KEY}}}
