name: GitHub CI/CD
on: push

jobs:
  build:
    runs-on: self-hosted
    steps:

    - uses: actions/checkout@v2

    - name: Set environmental variables
      uses: allenevans/set-env@v1.1.0
      with:
        REF_TAG: ${{env.GITHUB_REF#refs/tags/}}

    - name: DSharp4Webhook Build (Mono)
      shell: pwsh
      run: pwsh ./scripts/build.ps1 true ${env:REF_TAG}

    - name: DSharp4Webhook Build
      shell: pwsh
      run: pwsh ./scripts/build.ps1 false ${env:REF_TAG}

  deploy:
    runs-on: self-hosted
    needs: build
    steps:

    # Making a release if it is a tag
    - name: GitHub Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: Release ${{env.REF_TAG}}
        files: |
          deploy/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Push NuGet if it is a tag
    - name: NuGet Push
      if: startsWith(github.ref, 'refs/tags/')
      run: Get-ChildItem -Path "./deploy/" -File -Recurse | Where-Object Name -Match ".+\.nupkg" | % {dotnet nuget push $_.FullName -s nuget.org -k ${{secrets.NUGET_API_KEY}}}
