name: GitHub CI/CD
on: push

jobs:
  build:
    runs-on: self-hosted
    steps:

    - uses: actions/checkout@v2

    - name: Tag getter
      uses: olegtarasov/get-tag@v2
      with:
        tagRegex: "(\\d+\\.\\d+\\.\\d+)"

    - name: DSharp4Webhook Build
      shell: pwsh -File {0}
      run: ./scripts/build.ps1 ${env:GIT_TAG_NAME}

  deploy:
    runs-on: self-hosted
    needs: build
    steps:

    # Making a release if it is a tag
    - name: GitHub Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          deploy/*.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Push NuGet if it is a tag
    - name: NuGet Push
      if: startsWith(github.ref, 'refs/tags/')
      run: Get-ChildItem -Path "src\" -File -Recurse | Where-Object Name -Match ".+\.nupkg" | % {dotnet nuget push $_.FullName -s nuget.org -k ${{secrets.NUGET_API_KEY}}}
