name: Build

on: push

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    # Getting the last tag
    - name: Tag script
      id: tag
      uses: actions/github-script@0.9.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const data = await github.repos.getLatestRelease({owner:context.repo.owner, repo:context.repo.repo});
          return data.data.tag_name;

    - name: Build
      run: dotnet build -c Release /p:VersionSuffix=dev /p:BuildNumber=${env:build} /p:VersionPrefix=${env:tag}
      env:
        tag: ${{steps.tag.outputs.result}}
        build: ${{github.run_number}}
