name: DSharp4Webhook CI
on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.6.0

    - name: Git Checkout
      uses: actions/checkout@v2.3.2

    - name: Restore packages
      run: dotnet restore

    - name: Build
      run: dotnet build -c release

    - name: Manage build result
      shell: pwsh
      run: |
        New-Item -Path 'deploy' -ItemType Container
        Get-ChildItem -Path 'src\' -Directory -Recurse | Where-Object { $_.FullName.EndsWith("bin\Release") } | ForEach-Object {
            $ProjectName = $_.FullName.Split('\')[-3]
            Get-ChildItem -Path $_.FullName -Directory -Recurse | ForEach-Object {
                $FrameworkName = $_.Name
                $FinalName = "$ProjectName-$FrameworkName"
                $OutputPath = Join-Path $DeployPath $FinalName
                New-Item -Path $OutputPath -ItemType Container
                Copy-Item -Path ($_.FullName + "\*") -Destination $OutputPath -Recurse -Force
            }
        }

    - name: Upload DSharp4Webhook.Rest.Mono-net471
      uses: actions/upload-artifact@v2
      with:
        name: DSharp4Webhook.Rest.Mono-net471
        path: deploy/DSharp4Webhook.Rest.Mono-net471

    - name: Upload DSharp4Webhook-net471
      uses: actions/upload-artifact@v2
      with:
        name: DSharp4Webhook-net471
        path: deploy/DSharp4Webhook-net471

    - name: Upload DSharp4Webhook-netstandard2.0
      uses: actions/upload-artifact@v2
      with:
        name: DSharp4Webhook-netstandard2.0
        path: deploy/DSharp4Webhook-netstandard2.0
