name: Deploy

on:
  push:
    tags:
      '*'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Pack
      run: dotnet pack -c Release

    # PowerShell time
    - name: Deploy
      run: Get-ChildItem -Path "./src/bin/Release/" -Recurse | Where-Object Name -Match ".+\.nupkg" | % {dotnet nuget push $_.FullName -s nuget.org -k ${{secrets.NUGET_API_KEY}}}
